### ISSUE TITLE
In 1.1.0.0(1.1.0.1), there is no appearance of the following type of work after the execution of the previous contract.

### ISSUE THREAD

**Issue by vitalii2011** [Royal-Modding/FS19_BetterContracts#10]
In 1.0.0.0 it was very convenient, the following type of work appeared immediately: https://drive.google.com/file/d/1bRwyGgmvY3Thc-W4WE2PJGWvOilGZkK2/view?usp=sharing or sometimes, very rarely so: https://drive.google.com/file/d/1_W3-SX4lQFHtqmYGS5jdcFTaB2spjV2K/view?usp=sharing 
In new versions, you have to "clean" the list and update it several times: https://drive.google.com/file/d/1bXK9O9JGIVlg5zK115GgWhcTPrzcY3GS/view?usp=sharing It became very uncomfortable.

**Comment by TyKonKet** [comment]
@vitalii2011 I can totally agree with you that this is very uncomfortable, but at the moment I have really no clue why it happens, I will investigate it.

**Comment by mhausberg** [comment]
This may be solved by the latest #11 merge.
 If I understand the 2nd video correctly, the New-Contracts button may not produce any contracts, because the max # of contracts on this map was reached.

**Comment by TyKonKet** [comment]
https://github.com/Royal-Modding/FS19_BetterContracts/releases/tag/1.2.0.0-RC3

**Comment by vitalii2011** [comment]
> 
> 
> https://github.com/Royal-Modding/FS19_BetterContracts/releases/tag/1.2.0.0-RC3

- The secret of the contracts is finally revealed. Now it will not be "buying a pig in a poke"("buying a cat in a bag", - in the Russian lexicon). ) 
- l10n_ru.xml for Better Contracts(1.1.0.3) https://pastebin.com/UmubYDf4 
- Can't you increase the space for a word from line 15 by 2 characters? There should be: "Фильтр" https://i.imgur.com/YYlHTuc.png , but I had to shorten it to "Ф-тр", and this is not very nice and clear. If this is difficult, then can delete this line("<text name="SC_sort" text="Ф-тр" />") to pick up the English version.

**Comment by mhausberg** [comment]
will be addressed in #20
