### ISSUE TITLE
Not enough space for long translated words on details box

### ISSUE THREAD

**Issue by mhausberg** [Royal-Modding/FS19_BetterContracts#20]
I will handle this as a separate issue, and therefore close #10 . The issue also happens in other languages (Italian, French), when translated words are longer than the English one, e.g. "width/ height" --> "Largeur, Longueur".
My first try to address it: simply decrease text size. Since I do not want to mess with the original screen setup to much. We will see how it looks ..

**Comment by mhausberg** [comment]
@Lactic68 - thanks for the French translation. Some of the main button names are too long, they won't fit the screen:
![french-details](https://user-images.githubusercontent.com/51960039/116424943-3676df00-a842-11eb-815d-5ec3598a85ed.png)

Otherwise, the smaller (14px) details display texts are readable ok. What do you think?

**Comment by Lactic68** [comment]
@mhausberg Hi,
Thank you for your notice. I just have submitted updated translation to reduce text length :)

**Comment by mhausberg** [comment]
translations are complete, and fit the UI screen.
