### ISSUE TITLE
Type of contract "snow cleaning"

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Royal-Modding/FS19_BetterContracts#25]
It seems to me you forgot about the not very common type of contract as "snow cleaning." (type="snow") It appears with the seasons, and if a map has been prepared.
FS19_BetterContracts/betterContracts.lua:363: attempt to compare nil with number

**Comment by ghost** [comment]
You're right - I didn't think of that mission type. I will update the code to include it. Thanks for testing!

Edit:
Update included in latest commit to main. (And in RC-4). Please test.
