### ISSUE TITLE
Error in mod

### ISSUE THREAD

**Issue by Bandesss** [Royal-Modding/FS19_BetterContracts#26]
Hello I have problems when enlisting at 100% of the order is settled but remains in the list. I also use missionbalance hope you can help me version of you the current one from Github

![1](https://user-images.githubusercontent.com/50829319/124153768-11e2f180-da95-11eb-81fe-5a594344701a.png)
Greets

**Comment by mhausberg** [comment]
Hi - I have not tested compatibility with "missionbalance" - Can you give me a link to that mod?
Also, for further error analysis, could you attach your log.txt here?

**Comment by Bandesss** [comment]
I'll link the log tomorrow. Even without the Morebalance mod, your mod won't work. The mod is from DerElky from the Hot Team

**Comment by mhausberg** [comment]
Thanks for the log. I assume that bug 
```
2021-07-02 17:38 Error: Running LUA method 'update'.
2021-07-02 17:38 F:/Kandelin/FS19_BetterContracts/betterContracts.lua:180: attempt to get length of a nil value
```
(1st error occurs when loading custom mission vehicles) was fixed in the latest version. Please [download](https://github.com/Royal-Modding/FS19_BetterContracts/releases/tag/1.2.0.0-RC3) here, and try if that error still comes up.

**Comment by Bandesss** [comment]
Ok, with you new Mod comes this Picture
![1](https://user-images.githubusercontent.com/50829319/124353932-bc7c2100-dc09-11eb-986e-12c5c1c893a0.png)

**Comment by mhausberg** [comment]
Kommt mir bekannt vor. Hatte ich bei der Entwicklung auch ab und zu. Kannst du noch mal die Log.txt schicken (ich nehme an, dass du deutsch verstehst)?

**Comment by Bandesss** [comment]
Deutsch ist mir lieber :) 
[log.txt](https://github.com/Royal-Modding/FS19_BetterContracts/files/6758480/log.txt)

**Comment by mhausberg** [comment]
Hm- der Fehler 
`2021-07-03 14:19   Error: F:/Kandelin/FS19_BetterContracts/scripts/userint.lua:85: bad argument #1 to 'ipairs' (table expected, got nil)
` 
bezieht sich auf Zeile 85 in userint.lua:
`for _, v in ipairs(m.vehiclesToLoad) do`

Der Fehler passiert, wenn es für eine Feldmission keine Mietfahrzeuge gibt. Und das kann wiederum nur passieren, wenn man einen Spielstand mit custom Mission-Fahrzeugen lädt (die das aktuelle Spiel nicht kennt). Ist sozusagen ein Folgefehler vom ersten Fehler in der ersten Log von gestern.
Anyway, ich werd das dann im Code abfangen und schick dir eine neue Version zum Testen.

**Comment by Bandesss** [comment]
OK also dir Fahrzeuge gehören aber mir.
Ohne deinen Mod ist das Spiel nicht das selbe 👍

**Comment by Lahmi** [comment]
Moin, im MP gibt es auch einen Error gleiches Bild wie oben" zur Zeit keine Lohndienstleistungen möglich". [log.txt](https://github.com/Royal-Modding/FS19_BetterContracts/files/6759505/log.txt)

**Comment by mhausberg** [comment]
@Bandesss , geht um die Fahrzeuge, die dir bei jeder Feldmission (Transportmissionen nicht) zur Miete angeboten werden.  Da wird vom Spiel immer mindestens 1 generiert.

@Lahmi, deine Log zeigt einen anderen Fehler: eine Erntemission hat keinen Eintrag für die erwartete Menge, das darf normalerweise auch nicht vorkommen.

Hab jetzt mal diese beiden Situationen im Code abgefangen, aber ggf sind das nur Folgefehler von etwas anderem .. Bitte testet mal dieses https://github.com/Royal-Modding/FS19_BetterContracts/releases/tag/1.2.0.0-RC4. Es enthält debug Meldungen in der Log, außerdem könnt ihr bei Auftreten von Fehlern mal auf der Konsole den Befehl `printBetterContracts` eingeben.

**Comment by Bandesss** [comment]
Hallo ist es so richtig ?
[log.txt.txt](https://github.com/Royal-Modding/FS19_BetterContracts/files/6759763/log.txt.txt)

**Comment by Lahmi** [comment]
So Error besteht weiterhin. 
[log.txt](https://github.com/Royal-Modding/FS19_BetterContracts/files/6759780/log.txt)

**Comment by mhausberg** [comment]
@Bandesss, ja die Log sagt was aus:
1. die Gras-Missionen auf Feld 35 und 36 sind kaputt. Bzw. das Spiel findet die dafür vorgesehenen Mietgeräte nicht.
2. Beim Laden der Default Mietgeräte (da bringt BetterContracts ja auch seine eigenen mit) geht eine Kleinigkeit schief: `F:/Kandelin/FS19_BetterContracts_Kandelin/betterContracts.lua:182: attempt to get length of a nil value`

Kannst du daher mal folgende Files hochladen:
`missions.xml` aus dem aktuellen savegame Ordner
`baseGame.xml, claasPack.xml` aus dem Ordner FS19_BetterContracts_Kandelin/missionVehicles (nur falls ihr da was geändert haben solltet ::)

@Lahmi, das ist im Prinzip der gleiche Fehler, jetzt für eine Grasmission. Da brauch ich für die Analyse noch etwas, aber deine missions.xml aus dem aktuellen savegame Ordner würde auch helfen.

**Comment by Bandesss** [comment]
Kann ich hochladen, aber wie gesagt sind eigene Fahrzeuge also ich hab sie inagme gekauft lol
Ich lade sie hoch

**Comment by Lahmi** [comment]
So nun auch von mir die Mission.xml. 
[missions.zip](https://github.com/Royal-Modding/FS19_BetterContracts/files/6760270/missions.zip)

**Comment by mhausberg** [comment]
Hm- an der missions.xml kann ich erst mal nix Verdächtiges erkennen. 
@Bandesss, für die weitere Fehlersuche müsstest du mal FS19_EasyDevControls in den mod Ordner nehmen, und dann an der Konsole eingeben:
`printTable g_missionManager.missionVehicles.mow_bale 1 5`
und mir dann wieder die log.txt schicken.

Oder auch mal deinen savegame-Ordner zippen und hier hochladen. Wenn das die Kandelin v1.5 ist, versuch ich sie mir auch grad zu laden. Dann könnte ich den Fehler bei mir ggf reproduzieren.

**Comment by Bandesss** [comment]
Ne ist die ganz neue Kandelin 2.1 :)

**Comment by Lahmi** [comment]
Hier auch meine log. 
[log.txt](https://github.com/Royal-Modding/FS19_BetterContracts/files/6760599/log.txt)

**Comment by mhausberg** [comment]
Ok, zumindest die von @Bandesss gemeldeten Fehler liegen daran, dass die Kandelin eine eigene missionVehicles.xml enthält, die nur für Missionen auf "large" Feldern eine Fahrzeug/ Geräte-Auswahl bereitstellt. D.h. wenn das Spiel dann Missionen auf kleineren Feldern generiert (17, 35, 36), werden keine Leihgeräte angeboten. Das kommt im Standardspiel nicht vor, und BetterContracts konnte damit bisher nicht umgehen. 
Jetzt schon: bitte mal dies [Pre-Relese](https://github.com/Royal-Modding/FS19_BetterContracts/releases/download/1.2.0.0-RC4/FS19_BetterContracts_Kandelin.zip) testen. Es enthält noch die DevWarnings in der Log, die Missionen sollten aber korrekt angezeigt werden.

Das MP Verhalten teste ich gerade noch.

**Comment by Bandesss** [comment]
Ich hatte es auf der Steffishausen versucht ohne Probleme.
Danke für eure Mühe und Zeit

**Comment by Lahmi** [comment]
Das stimmt ich habe die aktuellste Kandelin  abgeändert und sie auf die standart Missions Pfad abgeändert damit ich auch die Fahrzeuge nutzen kann die ich als Missionsfahrzeuge haben möchte. Natürlich habe ich aber auch die small Fahrzeuge raus genommen. Dies ist vielleicht ein Ansatz für mich.

**Comment by Lahmi** [comment]
So ich hab die neust version auf der Kandelin im MP getestet. Nun klappt es!!! :-) vielen Dank dafür Gruß

**Comment by Bandesss** [comment]
Top ich danke euch :)

**Comment by Lahmi** [comment]
Eine Frage habe ich noch. Gibt es die Möglichkeit wenn man die basegame und claas dlc Fahrzeuge ändert, nur die geänderten nutzen zu können? Da ich für eine 4 Fach Map immer mehrere Fahrzeuge in eine Mission packe. Möchte für MP nicht ein Schlepper mit einem Pflug auf ein Feld der Größe von über 50ha. Desweiteren ändere ich auch immer noch in der config <configuration name="buyableGPS" id="2"/> da viele noch mit diesem Mod spielen und es somit standartmäßig in Missionsfahrzeugen fehlt. Es stört auch nicht wenn der Mod nicht installiert ist meines Wissens.

Danke 👍

**Comment by mhausberg** [comment]
Ok- also du meinst, dass die Missionsfahrzeuge aus dem Standardspiel (oder der Karte, wenn sie eigene missionVehicles.xml hat) komplettt überschrieben werden durch die missionVehicles/baseGame.xml und /claasPack.xml im BetterContracts mod Ordner. Ich glaub das hat Matteo schon mal für dich eingerichtet, für FS19_ThueringerHoehe.

Das kann ich einbauen, dann müsstest du in der ersten Zeile der baseGame.xml das Überschreiben der Standard-Fahrzeuge einschalten:
`<missionVehicles overwrite="true">`
Damit hast du dann aber auch die Verantwortung, dass es für jeden Missionstyp (harvest, sow, fertilize, ...) auf jeder Feldgröße der Karte (small, med, large) mindestens ein Fahrzeug-Set ("group") gibt 😉. Das Spiel generiert die Missionen in etwa so:
- gehört das Feld einem NPC?
- welcher Missionstyp würde gehen? (z.B. wenn Wachstumstatus erntereif -> harvest mission)
- Feldgröße in ha? 0-1.5 : small. 1.5-5 : medium. > 5 : large
- Such mir aus der missionVehicles.xml eine `<group>` mit dem passenden `mission type` und der passenden `fieldsize` (und bei harvest missions muss auch noch `variant` zum Fruchttyp passen)
Falls eine Karte also nur Felder > 5 ha hat, braucht man nur "large" Einträge. (Haben die Kandelin-Bauer so gemacht, aber vergessen, dass die Karte auch ein paar medium Felder enthält (17,35,36).

Ja,  hab n bisschen was an der Sortierung gedreht, damit die Verträge ohne Prof-pro-min (Transport, Schneeräumen) auch sortiert werden. Dabei hab ich ggf nicht an so hohe  Prof-pro-min Werte gedacht, wie sie bei 50 ha Missionen auftreten. Schick mal n screenshot bitte!

**Comment by Lahmi** [comment]
Moin, ja die Thüringer wurde freundlicher weise für mich angepasst, vielen Dank nochmal dafür.

Mit den Fahrzeugen ist kein Problem für mich. Eine Frage ist aber noch ob eine Möglichkeit besteht Mods aus dem Mod Ordner mit einbeziehen zu können.

Die Bilder der Sortierung schicke ich heute Abend da ich noch auf der Arbeit bin. Gruß Lahmi

**Comment by Lahmi** [comment]
Nun einmal die Standartansicht wo aktuell nichts richtig sortiert ist! [Sortierung](https://user-images.githubusercontent.com/86673802/124649850-4f7eba80-de99-11eb-95b1-5af5d587a841.png)

**Comment by Lahmi** [comment]
Hier noch eine ![Sortierung_1](https://user-images.githubusercontent.com/86673802/124660947-2a914400-dea7-11eb-83ae-a99145b38194.png)

**Comment by ghost** [comment]
Nabend,
in der Standardansicht (Details aus) sind die Missionen vom Standardspiel sortiert, nach Alter. In der Mod-Ansicht (Sort. Missionstyp/Feldnr) hab ich die Sortierung angepasst, alle Missionen eines Typs sind jetzt beieinander. Die Typen sind auch in Gruppen sortiert: 
- erst Ernte, 
- dann die "Verbrauchs-Missionen" Säen, Düngen, Spritzen, 
- dann die einfachen Missionen Pflügen, Grubbern, Unkraut
- Gras-Missionen = Ballen pressen
- zuletzt non-Feld Missionen Transport, Schneeräumen (Seasons)

Außerdem hab ich versucht, deinen Request 
> 
> Gibt es die Möglichkeit wenn man die basegame und claas dlc Fahrzeuge ändert, nur die geänderten nutzen zu können? Da ich für eine 4 Fach Map immer mehrere Fahrzeuge in eine Mission packe.
>
umzusetzen. Dazu musst du im entpackten BetterContracts die missionVehicles/userDefined.xml überschreiben, also **nicht** die baseGame und claasPack xmls. Wenn du in der 2. Zeile `overwrite=true` setzt, sind deine die einzigen Missionsfahrzeuge im Spiel.

> Desweiteren ändere ich auch immer noch in der config für den Mod FS19_guidanceSteering, configuration name="buyableGPS" id="2" da viele noch mit diesem Mod spielen und es somit standartmäßig in Missionsfahrzeugen fehlt. Es stört auch nicht wenn der Mod nicht installiert ist meines Wissens.
> 
Doch, das gibt Log-Fehler. Bei Mod-Fahrzeugen und Mod-Configurations solltest du daher immer den benötigten Mod mit angeben, also z.B. `requiredMod="FS19_guidanceSteering"` (s. Beispiel in userDefined.xml).

So, hier das neueste [Pre-Release](https://github.com/Royal-Modding/FS19_BetterContracts/releases/download/1.2.0.0-RC4/FS19_BetterContracts.zip) zum Testen.
PS. Guck dir auch mal #16 an, zum selben Thema 😉

**Comment by Lahmi** [comment]
Vielen vielen Dank für die Arbeit mit dem Mod und deren Anpassung.
