### ISSUE TITLE
Fehler Server 

### ISSUE THREAD

**Issue by Bandesss** [Royal-Modding/FS19_BetterContracts#27]
Hallo unsere Neue Map, hat Fehler mit Eurem Mod
2021-07-18 11:18   Warning: [FS19_BetterContracts]:getFromVehicle() could not find appropriate vehicle in mission 399. Last vehicle: TRAILERS strautmann/SEK802/SEK802.xml
Anbei die ganze Log 
[log.txt](https://github.com/Royal-Modding/FS19_BetterContracts/files/6835929/log.txt)
Gruß

**Comment by ghost** [comment]
Moin,
könnte sein, dass das ein Folgefehler ist von
`2021-07-18 11:14   Warning: [FS19_BetterContracts] required Mod FS19_claasDominator108SL not found, ignoring mission vehicle vehicles/claas/dominator108SL/dominator108SL.xml
`
Der Dominator ist nur als Beispiel für eine benutzerdefiniertes Mission Fahrzeug gedacht, siehe userDefined.xml im /missionVehicles Verzeichnis des Mod. Wenn ihr das nicht braucht, einfach die Datei `userDefined.xml` im FS19_BetterContracts.zip löschen!

Andererseits braucht mein Code auch die Warnmeldung mit `getFromVehicle() could not find appropriate vehicle in mission 397. Last vehicle: TRAILERS strautmann/SEK802/SEK802.xml` andauernd zu wiederholen. Guck ich mir an.

**Comment by Bandesss** [comment]
Versuche ich Danke

**Comment by ghost** [comment]
Scheint geklappt zu haben ;)

**Comment by Bandesss** [comment]
Passt alles gut, hatte vergessen zu schreiben sorry
