### ISSUE TITLE
Fehler wieder mal

### ISSUE THREAD

**Issue by Bandesss** [Royal-Modding/FS19_BetterContracts#29]
Hallo zusammen ich habe was ganz neues
[log.txt](https://github.com/Royal-Modding/FS19_BetterContracts/files/6955972/log.txt)
Hoffe ihr könnt mir helfen ?!
Gruß

**Comment by ghost** [comment]
Moin,
falls das noch akut ist - ich vermute ein kaputte savegame (Missionen / Missionsfahrzeuge). Passiert das auch bei einem neuen Spielstand?
`betterContracts.lua:380: attempt to perform arithmetic on field 'expectedLiters' (a nil value)`

**Comment by Bandesss** [comment]
Ja hat sich erledigt, sorry
Wird es noch ne neue Version für den ls 19 geben ?
Gruß
Bleibt Gesund
