### ISSUE TITLE
No permission for this land / borrowed - own vehicles

### ISSUE THREAD

**Issue by LawAcidFlash** [Royal-Modding/FS19_BetterContracts#5]
Hello Royal-Modding,

Issue: Can't do missions with own vehicles - Message "No permission for this land" Hope the translating ist correct, we have german. Not able to cultivate mission field.
What caused this issue. We are not 100% sure but we thik it happens when we use borrowed vehicles from the mission and own ones, Happend after we cleared the available missions and generated new ones. from this moment we can do missions only with borrowed Mission Vehicles.

Solution: Clear all missions, remove Mod, restart Server, remove missions, restart Server - looks OK

What do we have
Dedicated Server with map: Untergriesbach
Season
Precision Farming
Manure
MaizePlus
Global Company
VCA

Best regards
Tobi

**Comment by LawAcidFlash** [comment]
Hello Royal-Modding,

just read in an older bug report that he had also the issue with no acces to land when he accepted to many contracts, maybe this could also be the issue cause we accept more than 5 to 10 missions.

BR
Tobi

**Comment by TyKonKet** [comment]
Hello @LawAcidFlash 
That's a know issue that can happen when you have more than one mission active, it happens mostly on MP games.
We aren't still able to fix it, but considering the same issue happens on other mods that allows to accept multiple contracts, we are pretty sure it depends on something wrong with the base game.
We are so sorry but we aren't able to solve your problem currently, however sometimes simply cancelling the contract and accepting a new one it's enough to fix the issue.
